server:
  port: 10010
spring:
  cloud:
    gateway:
      routes:
      - id: foods_route
        uri: lb://exam-service
        predicates:
        - Path=/
        filters:
        - StripPrefix=1
        order: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka